# Permalinks
permalink: /:title/
relative_permalinks: false

show_excerpts: false  # set to true to show excerpts on the homepage

# Setup
title: AB

author:
  name: An Be

# Custom vars
theme: minima

minima:
  # generate social links in footer

book_links:
  default:
    book1: "https://www.amazon.com/book1"
    anotherbook: "https://www.amazon.com/anotherbook"
  uk:
    book1: "https://www.amazon.co.uk/book1"
    anotherbook: "https://www.amazon.co.uk/anotherbook"


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 
header_pages:
  - about.md
